all:
	g++ ex01.cpp -o ex01 -std=gnu++0x -O3 -g ../src/sockets/*Socket.cpp -I/usr/include/jsoncpp/ -l jsoncpp
	g++ ex02.cpp -o ex02 -std=gnu++0x -O3 -g ../src/sockets/*Socket.cpp -I/usr/include/jsoncpp/ -l jsoncpp
